services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - redis
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - hsk_chatbot

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__STORAGE__PATH: "/qdrant/storage"
      QDRANT__COLLECTIONS__INTERNAL_API__ENABLED: "true"
      QDRANT__LOG__LEVEL: "info"
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    restart: unless-stopped
    networks:
      - hsk_chatbot

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - hsk_chatbot

volumes:
  qdrant_data:
  redis_data:

networks:
  hsk_chatbot:
    external: true
