services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - moonology


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - moonology

volumes:
  redis_data:

networks:
  moonology:
    external: true
